apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        command: ["docker-entrypoint.sh", "bin/sh"]
        args: ["rabbitmq-server","rabbitmq-plugins enable rabbitmq_management"]
        ports:
        - containerPort: 4369
          name: peer-discovery
          protocol: TCP
        - containerPort: 15672
          name: mgmt-console
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
